// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFJ0gfrK3cKooMMwXpHd_5OQ5KVQnh2Q',
    appId: '1:856215702177:web:62297b53e465f49f5dbee0',
    messagingSenderId: '856215702177',
    projectId: 'cargo58',
    authDomain: 'cargo58.firebaseapp.com',
    storageBucket: 'cargo58.firebasestorage.app',
    measurementId: 'G-1DWLZ1W524',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgKYVllhR-chrTYazbkT-YXfAx_VM5vaA',
    appId: '1:856215702177:android:b98555013610941c5dbee0',
    messagingSenderId: '856215702177',
    projectId: 'cargo58',
    storageBucket: 'cargo58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKuW3P9ZGlSdM5muyvvuXgNd2eayq5ELY',
    appId: '1:856215702177:ios:4b9b4bc0ac8c143f5dbee0',
    messagingSenderId: '856215702177',
    projectId: 'cargo58',
    storageBucket: 'cargo58.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKuW3P9ZGlSdM5muyvvuXgNd2eayq5ELY',
    appId: '1:856215702177:ios:4b9b4bc0ac8c143f5dbee0',
    messagingSenderId: '856215702177',
    projectId: 'cargo58',
    storageBucket: 'cargo58.firebasestorage.app',
    iosBundleId: 'com.example.cargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGFJ0gfrK3cKooMMwXpHd_5OQ5KVQnh2Q',
    appId: '1:856215702177:web:ae7e77f5044f5cd75dbee0',
    messagingSenderId: '856215702177',
    projectId: 'cargo58',
    authDomain: 'cargo58.firebaseapp.com',
    storageBucket: 'cargo58.firebasestorage.app',
    measurementId: 'G-BLX2MRLN4V',
  );

}